name: Build and push to Artifact Registry

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  GAR_LOCATION: https://us-central1-python.pkg.dev/creditriskmlops/python-packages-repo
  GCP_CREDENTIALS: '${{ secrets.SERVICE_ACCOUNT_KEY }}'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.9'
    - name: Install Poetry and Twine
      run: | 
        python3 - -y
        python3 -m pip install twine
        python3 -m pip install poetry
    - name: Configure Poetry
      run: python3 -m poetry install --sync --no-interaction
    - name: Auth to GCP
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
    - name: Run Poetry Build
      run: poetry build  
    - name: Set up Artifact Registry and upload
      run: |
        gcloud config set project creditriskmlops
        gcloud config set artifacts/repository python-packages-repo
        gcloud config set artifacts/location us-central1
        echo "$GCP_CREDENTIALS" | gcloud auth activate-service-account --key-file=/dev/stdin
        python3 -m twine upload --repository-url $GAR_LOCATION/ dist/* \
          --username _json_key \
          --password "$GCP_CREDENTIALS"
        
